# This YAML configuration file holds the default values used for configuring 3D sensors.
# The name of this file shouldn't be changed, or else the Setup Assistant won't detect it.
# Values may not be ideal defaults, original source unclear.
sensors:
  - sensor_plugin: occupancy_map_monitor/PointCloudOctomapUpdater
    point_cloud_topic: /camera/depth/color/points
    max_range: 5.0
    point_subsample: 1
    padding_offset: 0.1
    padding_scale: 1.0
    max_update_rate: 1.0




